In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.26.4


In [ ]:
A1=np.array([1,2,3,4])
print(A1)

[1 2 3 4]


In [ ]:
type(A1)

numpy.ndarray

In [ ]:
A1.shape

(4,)

In [ ]:
A1.size

4

In [ ]:
A1.ndim

1

In [ ]:
A2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(A2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
type(A2)

numpy.ndarray

In [ ]:
A2.size

10

In [ ]:
A2.shape

(2, 5)

In [ ]:
A2.ndim

2

In [ ]:
A3=np.array([[[1,2,3,],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(A3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
type(A3)

numpy.ndarray

In [ ]:
A3.shape

(2, 3, 3)

In [ ]:
A3.size

18

In [ ]:
A3.ndim

3

In [ ]:
A4=np.array([[[[1,2,3],[4,5,6],[7,8,9]]],[[[1,2,3],[4,5,6],[7,8,9]]]])
print(A4)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [ ]:
A4.shape

(1, 1, 3, 3)

In [ ]:
A4.size

9

In [ ]:
A4.ndim

4

In [ ]:
#zero array
A5=np.zeros(2)
print(A5)

[0. 0.]


In [ ]:
A6=np.zeros((3,3),int)
print(A6)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
A7=np.zeros((2,3,3),int)
print(A6)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#one array
A8=np.ones(2)
print(A5)

[1. 1.]


In [ ]:
A9=np.ones([3,3],int)     #for ones we use square backet
print(A9)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
from re import A
#full array
A10=np.full(2,5)
print(A10)

[5 5]


In [ ]:
A11=np.full([3,3],5,dtype=float)     #for full we use square backet
print(A11)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [ ]:
A12=np.full([3,3],6,dtype=float)
print(A12)

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [ ]:
ad=np.add(A11,A12)
print(ad)

[[11. 11. 11.]
 [11. 11. 11.]
 [11. 11. 11.]]


In [ ]:
su=np.subtract(A11,A12)
print(su)

[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]


In [ ]:
mu=np.multiply(A11,A12)
print(mu)

[[30. 30. 30.]
 [30. 30. 30.]
 [30. 30. 30.]]


In [ ]:
di=np.divide(A11,A12)
print(di)

[[0.83333333 0.83333333 0.83333333]
 [0.83333333 0.83333333 0.83333333]
 [0.83333333 0.83333333 0.83333333]]


In [ ]:
dimo=np.mod(A11,A12)
print(dimo)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [ ]:
po=np.power(A11,A12)
print(po)

[[15625. 15625. 15625.]
 [15625. 15625. 15625.]
 [15625. 15625. 15625.]]


In [ ]:
#print array with alternative elements for 3d
np.full([2,7,8,9,6],[71,72,71,72,71,72],dtype=float)

array([[[[[71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.],
          ...,
          [71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.]],

         [[71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.],
          ...,
          [71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.]],

         [[71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.],
          ...,
          [71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.]],

         ...,

         [[71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.],
          [71., 72., 71., 72., 71., 72.],
          ...,
          [71., 72., 71., 72., 71., 7